version: "3.8"

services:
  app: 
    build: .
    container_name: fin-api
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/app
    depends_on:
      - postgres
    networks:
      - fin-api-network
  postgres: 
    image: postgres:latest
    container_name: fin-api-postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: fin_api
      POSTGRES_USER: fin_api
      POSTGRES_PASSWORD: fin_api
    volumes:
      - pgdata:/data/postgres
    networks:
      - fin-api-network

volumes:
  pgdata:

networks:
  fin-api-network: